import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import List from './List'
import { Input } from 'antd';
import React from 'react';
import styled from 'styled-components';
import Main from './Main';

export default function Home() {

  const [songList, setSongList] = useState([
    '심청가-곽씨부인 품파는대목(품팔어서)',
    '심청가-심청이 낳는 대목(삼십삼천)',
    '심청가-곽씨부인 유언대목(가군의)',
    '심청가-상여 소리 대목',
    '심청가-주과포혜',
    '심청가-심봉사 탄식하는 대목(적적한)',
    '심청가-중타령(중올라간다)',
    '심청가-심봉사 미치는대목(허허내가미쳤구나)',
    '심청가-심청이 효심대목(후원의)',
  ]);

  return (
    <div className={styles.container}>
      <Head>
        <title>땅이에게 바치는 노래 리스트</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <Main className={styles.height} />



      <main className={styles.main}>
        <h1>완소리 판소리 리스트</h1>
        <List songList={songList}></List>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
